### ISSUE TITLE
upcoming Movies

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#126]
- [ ] double check that. Looks weird to me

  ```TS
   if (typeof dataNowPlayingMovies == 'string') {
  return <span>Error!</span>;
  }
  ```

**Comment by pastor90** [comment]
I close it because it was fixed already in the SearchBar component

**Comment by pastor90** [comment]
I close it because it was fixed already in the SearchBar component
