### ISSUE TITLE
Show Account Settings Page only if successfully logged in

### ISSUE THREAD

**Issue by verascheunert** [devhausleipzigacademy/camp9-midterm#143]
Show the account settings page only if the login was successful 

- [ ] Create a page telling the user to please login in order to see account settings and add a button leading to the login/signup page 
- [ ] Show the newly created page if the user is not logged in, otherwise show the AccountSettings Page

**Comment by mateusmorgado** [comment]
The app is only usable if the user is already logged in. No need for this issue
