### ISSUE TITLE
movie database

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#157]
running the seed command provides  you all now playing movies + generes and credits in the local db.

- [ ] write a route and controller to get actual playing movies (from local db)
- [ ] make sure you just send data to frontend which is needed
- [ ] implement pagination in controller 
- [x] write a route and controller to get movie  information by id (movie details)
- [x] write a route and controller to get movie by search Query (search input)
- [x] write a route and controller to get all bookmarked movies
- [x] write a route and contoller (post) to bookmark a movie
- [ ] make sure your frontend hooks are fitting the needings of the new created api

**Comment by mora-ehidne** [comment]
Hey i will be working on the routes/controller for the bookmarks! 
ppl can join in and work on the other tasks!
