### ISSUE TITLE
Fix small issues

### ISSUE THREAD

**Issue by manuelpastorringuelet** [devhausleipzigacademy/camp9-midterm#161]
#1 Account settings page:

- [x] The page does not fit our screen size, also the font is a bit too big?

- [ ] Throws a warning on logout: You should call navigate() in a React.useEffect(), not when your component is first rendered. 
- [x]  Has a console.log

#2 Login page:
- [ ]  On login, throws a Warning: Cannot update a component (RouterProvider) while rendering a different component (NavigationLayout). To locate the bad setState() call inside NavigationLayout, follow the stack trace as described

#3 MovieDetail page: - the MovieDetail page has some weird formatting, the cast & crew button sometimes gets squashed so its label splits into two rows?
- [ ]  Also, the page does not fit in our screen size

#4 Home page:
- [ ]  Make the user name appears instead of [User] and remove the placeholder image

#5 Genres page:
- [ ]  the page does not fit our screen size

**Comment by mora-ehidne** [comment]
Could be that this task got covered by my fix in #168 :

Throws a warning on logout: You should call navigate() in a React.useEffect(), not when your component is first rendered.
