### ISSUE TITLE
Movie Detail Page

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#20]
- [x] fetch Single Film by id
- [x] ~write components for the detail Page~
- [x] Implement Movie Detail Header (ask Estefani she created one)
- [x] Clicking on read more should lead to the external movie page
- [x] Cast Crew button should Link to Cast Page
- [x] Get reservation should lead to times (dates) Page

**Comment by mateusmorgado** [comment]
I am interested. who want to join?

**Comment by mateusmorgado** [comment]
We are not doing single components, but doing everything on a page, because the elements won't be used anywhere else.

**Comment by mateusmorgado** [comment]
We are done with this
