### ISSUE TITLE
Home Page | Genre component

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#4]
- [x] Create a toggle able Icon button
- [x] Implement styling and genre component
- [x] Implement routing for "See all" Link
- [x] Create Genre Page
- [x] Implement counting of the different genres
- [x] create Object which maps genre name to icons ("emoji")
- [x] Implement the go back routing functionality

**Comment by estefaninoely** [comment]
done
