### ISSUE TITLE
React Query

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#43]
- [x] setup tanstack query in main.tsx
- [x] write a useGetMoviesHook
- [ ] use GET /movie/now_playing API Endpoint

**Comment by that-marty** [comment]
did the first point
 setup tanstack query in main.tsx  - [ x ] https://github.com/that-marty/camp9-midterm
write a useGetMoviesHook - [   ] 
use GET /movie/now_playing API Endpoint - [   ]

**Comment by DougInAMug** [comment]
Hey @that-marty thanks for your interest. I imagine you won't be able to submit a pull request to this repository - can you? If not I'll mention you in a commit message.
