### ISSUE TITLE
create movie detail hook

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#48]
- [x] create a movie detail react query hook
- [x] use the hook on movie detail page\
- [x] deactivate 'Get Reservation' button if movie unavailable
- [x] link 'Cast & Crew' button to appropriate page (Credits)
- [x] link to imdb, add target=_blank

**Comment by mora-ehidne** [comment]
hello person that works on this issue: pls let me know when u start working on the movie detail react query hook, as i will be needing to implement it in the credits page too!
