### ISSUE TITLE
Home Page | Upcoming Movies

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#5]
- [x] Implement styling for upcoming movie component
- [x] fetch data from tmdb API 
- [x] implement snapscrolling logic for movie images
- [x] implement routing to movie detail page

**Comment by RealBirdMan91** [comment]
hint: Use Tailwind for snapscrolling

**Comment by mateusmorgado** [comment]
TMDB.org
Username: class09
password: 2601 (day of first class)

-API Key (v3 auth): 
b83392e48747a4845ad80c2011eaa33b
-Example API Request: 
https://api.themoviedb.org/3/movie/550?api_key=b83392e48747a4845ad80c2011eaa33b
-API Read Access Token (v4 auth):
eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiODMzOTJlNDg3NDdhNDg0NWFkODBjMjAxMWVhYTMzYiIsInN1YiI6IjY0M2Q1NDk4ZDdhNzBhMDQ3YjE3MmE0MiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.6HjVYq_31EA5O1MN1VZ9pqsCdIZHjU4deoVntILu_-U

**Comment by mateusmorgado** [comment]
finished
