### ISSUE TITLE
create select seats page

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#53]
- [x] implement ui for select seats page and the components
- [x] seat rows are a-f and seat 0-7(in middle) and 0-5(front and back). "a-3"
- [x] create based on that logic an array of seats and display them
- [x] create 5 random selected Seats

**Comment by DougInAMug** [comment]
How's this going @NnekNnek and @Omanaite ? It seems all the tasks above are checked. (You should be able to edit the issue description to add more tasks if necessary)

**Comment by mateusmorgado** [comment]
Hey @Omanaite and @NnekNnek. Did you finish and merge this issue? Any updates

**Comment by DougInAMug** [comment]
I think this is done, was just hidden Routing by @mateusmorgado in #101 shows the page now.
