### ISSUE TITLE
movie list page

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#55]
- [x] create useGenreMovies hook
- [x] use the /discover/movie api
- [x] use the genre context to filter movies
- [x] show movies by genre
- [x] show a small tag list what are the filter conditions
- [x] work together with the genre context team (maybe the context has to adjust a lil bit)

**Comment by pilotmat** [comment]
sdadasdsad

**Comment by estefaninoely** [comment]
all issues done :)
