### ISSUE TITLE
Global Tailwind setup

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#7]
- [x] Add colors to Tailwind config
- [x] Add font to Tailwind config

**Comment by mora-ehidne** [comment]
Yeah, i think it makes sense to do it! I would add it to the body element!

**Comment by mora-ehidne** [comment]
OK i did it! 
  Finished the global CSS and Tailwind setup.
    Also downloaded the fonts to the public/fonts folder.
    Tailwind setup: added the colors from Figma in the config file.
    CSS:
    added the font imports,
    typography classes
    and background color of "dark" to the body tag.

Use the typography-title, typography-body, typography-primary, typography-secondary and typography-description for all your headings, paragraphs etc. If you are unsure which one to use, take a look in the figma file and compare to the Typography elements!

**Comment by DougInAMug** [comment]
@mora-ehidne what do you think about adding global padding too? looks like `px-3`, `py-6`. In the cases where we need to 'break out', we can use negative margins, or absolute positioning.
