### ISSUE TITLE
create Signup page

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#74]
- [x] implement toggle Btn like cast and crew page on the login screen
- [x] create functionality to switch between Login and Signup Page
- [x] create Singup Page
- [x] implement input fields email, password, 
- [x] student checkbox,
- [x]  radio button I'm 18 I'm not 18
- [x] signup btn should redirect to login page

**Comment by Quenayalui** [comment]
added name and lastname also as input field
