### ISSUE TITLE
Awesome infinite scroll

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp9-midterm#93]
- [x]  have a look for the  package react intersection observer an https://www.npmjs.com/package/react-intersection-observer
- [x] read the docs and observe the last movie element.
- [x] element should trigger a console.log("hai new movies") if its in view
- [x] remove the pagination implementation (comment out)

**Comment by Quenayalui** [comment]
finished infinite scroll hook and component
